### ISSUE TITLE
Cookie过期

### ISSUE THREAD

**Issue by Satoing** [lanzeweie/aolaxing#1]
请问你Cookie过期是怎么处理的呢？每次都要重新获取感觉挺麻烦，要是能账号密码登录就好了

**Comment by lanzeweie** [comment]
没办法，官方就只允许通过手机号验证码登录网站

**Comment by Satoing** [comment]
> 没办法，官方就只允许通过手机号验证码登录网站

我在想可不可以通过保持session的方式维持对话。思路就是一个进程保持24h登录，做任务的进程就用这个session去访问。我前几天试的，现在还没到cookie过期的时间，所以不太清楚是否可行。

通知我只在账号过期和可以换的时候才推送，所以用的很简单的bark。钉钉青龙啥的挺麻烦的，没法pr了😂

**Comment by lanzeweie** [comment]
更改模式了，你可以看看新代码，cookie 30天重置一次，保持维持对话，目前感觉是没有用的，百田就这副得行，纯摆烂，新开源的代码，我去年就在用了，到今年都没有修复

**Comment by Satoing** [comment]
嗯，应该不行，cookie指定了过期时间就莫法了。max-age我算下来是21天，不过总感觉没过几天就要更新一次，可能是因为跑的太多了。
