### ISSUE TITLE
自动兑换

### ISSUE THREAD

**Issue by Satoing** [lanzeweie/aolaxing#2]
请问你测试了兑换奥币的接口吗？
我觉得把 满600积分自动兑换 加到工作流里面会更好。

**Comment by lanzeweie** [comment]
有，但是百田上货是个问题，每天一次获得信息，也可能导致货被抢完，如果随时获取，万一影响到百田了，接口修改得不偿失。我本地用用就可以了

**Comment by Satoing** [comment]
行吧，下次换的时候我自己抓一下。
